/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekakhirpbo;

import static java.lang.Double.parseDouble;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABDAN SM
 */
public class ViewKasir extends javax.swing.JFrame {
    Connection cn = projekakhirpbo.Koneksi.Koneksi();
    ControllerKasir controller = new ControllerKasir();
    public Statement st;
   public ResultSet rs;
    public DefaultTableModel tabModel1;
    public DefaultTableModel tabModel2;
    public DefaultTableModel tabModel3;
    /**
     * Creates new form ViewKasir
     */
    public ViewKasir() {
        initComponents();
        start();
    }
    final void start(){
    jPanelTombol.setVisible(false);
    jPanelLogin.setVisible(true);
    jPanelMenuUtama.setVisible(false);
    jPanelTambahData.setVisible(false);
    jPanelUbahData.setVisible(false);
    jPanelNota.setVisible(false);
    }
    
    public void tabelHalamanUtama() {
  Object[] judul = {
    "id_produk","Nama Produk", "harga", "stok"
  };
  tabModel1 = new DefaultTableModel(null, judul);
  tabel1pembelian.setModel(tabModel1);
}
    
    public void tabelUbah() {
  Object[] judul = {
    "id_produk","Nama Produk", "harga", "stok"
  };
  tabModel2 = new DefaultTableModel(null, judul);
  tabel2ubah.setModel(tabModel2);
}
    
    public void tabelNota() {
  Object[] judul = {
    "Nama Produk", "harga", "kuantitas", "subTotal"
  };
  tabModel3 = new DefaultTableModel(null, judul);
  tabel3nota.setModel(tabModel3);
}
    
    public void tampilData(String like) {
  try {
    st = cn.createStatement();
    tabModel1.getDataVector().removeAllElements();
    tabModel1.fireTableDataChanged();
    rs = st.executeQuery("SELECT * FROM produk where nama_produk LIKE '%"+like+"%'");
    
    while (rs.next()) {
      Object[] data = {
        rs.getString("id_produk"),
        rs.getString("nama_produk"),
        rs.getString("harga"),
        rs.getString("stok"),
      };
        
        tabModel1.addRow(data);
    }
  } catch(Exception e) {
    e.printStackTrace();
  }
}
    
    public void tampilData() {
  try {
    st = cn.createStatement();
    tabModel2.getDataVector().removeAllElements();
    tabModel2.fireTableDataChanged();
    rs = st.executeQuery("SELECT * FROM produk");
    
    while (rs.next()) {
      Object[] data = {
        rs.getString("id_produk"),
        rs.getString("nama_produk"),
        rs.getString("harga"),
        rs.getString("stok"),
      };
        
        tabModel2.addRow(data);
    }
  } catch(Exception e) {
    e.printStackTrace();
  }
}
    
    public void tampilNota(){
    int akhir = controller.getJumlahBeli();
    tabModel3.getDataVector().removeAllElements();
    tabModel3.fireTableDataChanged();
    try{
    for(int i=0;i<akhir;i++){
    Object[] data = {
    controller.getNamaprod(i),
    String.valueOf(controller.getHargaprod(i)),
    String.valueOf(controller.getKuantitasprod(i)),
    String.valueOf(controller.getSubHargaprod(i))
    };
    tabModel3.addRow(data);
    }
    } catch(Exception e) {
    e.printStackTrace();
  }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTombol = new javax.swing.JPanel();
        btnHalamanUtama = new javax.swing.JButton();
        btnUbahProduk = new javax.swing.JButton();
        btnTambahProduk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanelLogin = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        fUsername = new javax.swing.JTextField();
        fPassword = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jPanelMenuUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lJumlahBeli = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1pembelian = new javax.swing.JTable();
        fSearchHalamanUtama = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        fKuantitas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        jPanelTambahData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fIDProduk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fNamaProduk = new javax.swing.JTextField();
        fHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fStok = new javax.swing.JTextField();
        btnTambahProd = new javax.swing.JButton();
        jPanelUbahData = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel2ubah = new javax.swing.JTable();
        fNamaUbah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fHargaUbah = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fStokubah = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanelNota = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lNamaKasir = new javax.swing.JLabel();
        lTotalHarga = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel3nota = new javax.swing.JTable();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelTombol.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHalamanUtama.setText("Halaman Utama");
        btnHalamanUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalamanUtamaActionPerformed(evt);
            }
        });

        btnUbahProduk.setLabel("Ubah Produk");
        btnUbahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahProdukActionPerformed(evt);
            }
        });

        btnTambahProduk.setLabel("Tambah Produk");
        btnTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTombolLayout = new javax.swing.GroupLayout(jPanelTombol);
        jPanelTombol.setLayout(jPanelTombolLayout);
        jPanelTombolLayout.setHorizontalGroup(
            jPanelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTombolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUbahProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHalamanUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(btnTambahProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTombolLayout.setVerticalGroup(
            jPanelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTombolLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnHalamanUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbahProduk)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Program Kasir Yurota Kampoeng");

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Selamat Datang!!");

        jLabel5.setText("username");

        jLabel6.setText("Password");

        btnLogin.setLabel("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin)
                    .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(168, 168, 168))
        );

        jPanelMenuUtama.setPreferredSize(new java.awt.Dimension(543, 344));

        jLabel3.setText("Halaman Utama Kasir");

        lJumlahBeli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lJumlahBeli.setText("Jumlah Jenis Produk yang dibeli = ");

        tabel1pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel1pembelian);

        btnSearch.setLabel("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        fKuantitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKuantitasActionPerformed(evt);
            }
        });

        jLabel8.setText("Kuantitas");

        btnBeli.setLabel("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuUtamaLayout = new javax.swing.GroupLayout(jPanelMenuUtama);
        jPanelMenuUtama.setLayout(jPanelMenuUtamaLayout);
        jPanelMenuUtamaLayout.setHorizontalGroup(
            jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                .addGroup(jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(fSearchHalamanUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                        .addGroup(jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(fKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBeli)
                            .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuUtamaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuUtamaLayout.setVerticalGroup(
            jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuUtamaLayout.createSequentialGroup()
                .addGroup(jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMenuUtamaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fSearchHalamanUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addGroup(jPanelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMenuUtamaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnBeli)))))
                .addComponent(lJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanelTambahData.setPreferredSize(new java.awt.Dimension(543, 344));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tambah Data Produk");

        jLabel7.setText("id_produk");

        jLabel9.setText("Nama_Produk");

        fNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaProdukActionPerformed(evt);
            }
        });

        jLabel10.setText("Harga");

        jLabel11.setText("stok");

        fStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fStokActionPerformed(evt);
            }
        });

        btnTambahProd.setLabel("Tambah Data");
        btnTambahProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTambahDataLayout = new javax.swing.GroupLayout(jPanelTambahData);
        jPanelTambahData.setLayout(jPanelTambahDataLayout);
        jPanelTambahDataLayout.setHorizontalGroup(
            jPanelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTambahDataLayout.createSequentialGroup()
                .addGroup(jPanelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTambahDataLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(fIDProduk)
                            .addComponent(fNamaProduk)
                            .addComponent(fHarga)
                            .addComponent(fStok, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addComponent(btnTambahProd))
                    .addGroup(jPanelTambahDataLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelTambahDataLayout.setVerticalGroup(
            jPanelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTambahDataLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fIDProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnTambahProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Ubah Data Produk");

        tabel2ubah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel2ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel2ubahMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel2ubah);

        fNamaUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaUbahActionPerformed(evt);
            }
        });

        jLabel13.setText("nama Produk");

        jLabel14.setText("harga");

        jLabel15.setText("Stok");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUbahDataLayout = new javax.swing.GroupLayout(jPanelUbahData);
        jPanelUbahData.setLayout(jPanelUbahDataLayout);
        jPanelUbahDataLayout.setHorizontalGroup(
            jPanelUbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUbahDataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanelUbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fNamaUbah)
                    .addComponent(fHargaUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(fStokubah, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGroup(jPanelUbahDataLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUbahDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        jPanelUbahDataLayout.setVerticalGroup(
            jPanelUbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUbahDataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelUbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUbahDataLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNamaUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fHargaUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fStokubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(jPanelUbahDataLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Nota Pembelian");

        lNamaKasir.setText("Nama Kasir  = ");

        lTotalHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lTotalHarga.setText("Total Harga =");

        tabel3nota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel3nota);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNotaLayout = new javax.swing.GroupLayout(jPanelNota);
        jPanelNota.setLayout(jPanelNotaLayout);
        jPanelNotaLayout.setHorizontalGroup(
            jPanelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotaLayout.createSequentialGroup()
                .addGroup(jPanelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNotaLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNotaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNotaLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(lTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBayar))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelNotaLayout.setVerticalGroup(
            jPanelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lNamaKasir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLayeredPane2.setLayer(jPanelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelMenuUtama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelTambahData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelUbahData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelNota, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanelMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanelTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelUbahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addComponent(jPanelNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTambahData, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelUbahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHalamanUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalamanUtamaActionPerformed
        tampilData("");
    jPanelMenuUtama.setVisible(true);
    jPanelTambahData.setVisible(false);
    jPanelLogin.setVisible(false);
    jPanelUbahData.setVisible(false);
    jPanelNota.setVisible(false);
    controller.nolkanJumlah(); 
    }//GEN-LAST:event_btnHalamanUtamaActionPerformed

    private void btnUbahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahProdukActionPerformed
         jPanelLogin.setVisible(false);
    jPanelTambahData.setVisible(false);
    jPanelMenuUtama.setVisible(false);
    jPanelUbahData.setVisible(true);
    jPanelNota.setVisible(false);
    tampilData();
    controller.nolkanJumlah(); 
    }//GEN-LAST:event_btnUbahProdukActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        controller.setUsername(fUsername.getText()); 
        String str2 = String.valueOf(fPassword.getPassword());
        boolean lanjut = controller.verifPass(str2);
        if(lanjut){
        jPanelLogin.setVisible(false);
    jPanelMenuUtama.setVisible(true);
    jPanelTambahData.setVisible(false);
     jPanelTombol.setVisible(true);
     tabelHalamanUtama();
     tabelUbah();
     tabelNota();
     tampilData("");
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String str1 = fSearchHalamanUtama.getText();
        tampilData(str1);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        
    jPanelMenuUtama.setVisible(false);
    jPanelTambahData.setVisible(false);
    jPanelLogin.setVisible(false);
    jPanelUbahData.setVisible(false);
    jPanelNota.setVisible(true);
    
    controller.hitungKasir();
    tampilNota();
    lNamaKasir.setText("Nama Kasir  = "+controller.getNamaKasir()+"");
    lTotalHarga.setText("Total Harga = "+controller.getTotalHargaprod()+"");
    
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdukActionPerformed
        lJumlahBeli.setText("Jumlah Jenis Produk yang dibeli = ");
        jPanelLogin.setVisible(false);
    jPanelMenuUtama.setVisible(false);
    jPanelTambahData.setVisible(true);
    jPanelUbahData.setVisible(false);
    jPanelNota.setVisible(false);
    controller.nolkanJumlah(); 
    }//GEN-LAST:event_btnTambahProdukActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        String id_prod = tabel1pembelian.getValueAt(tabel1pembelian.getSelectedRow(), 0).toString();
        String namaprod = tabel1pembelian.getValueAt(tabel1pembelian.getSelectedRow(), 1).toString();
        String hargaprod = tabel1pembelian.getValueAt(tabel1pembelian.getSelectedRow(), 2).toString();
        String stokprod = tabel1pembelian.getValueAt(tabel1pembelian.getSelectedRow(), 3).toString();
        String kuantitas = fKuantitas.getText();
        int jumlah = controller.getJumlahBeli();
        jumlah++;
        controller.setJumlahBeli(jumlah);
        lJumlahBeli.setText("Jumlah Jenis Produk yang dibeli = "+jumlah+"");
        controller.setKuantitas(Integer.parseInt(kuantitas), jumlah);
        controller.setIdProd(id_prod, jumlah);
        controller.setNamaProd(namaprod, jumlah);
        controller.setHargaProd(parseDouble(hargaprod), jumlah);
        controller.setStokProd(Integer.parseInt(stokprod), jumlah);
        fKuantitas.setText("");
        
        
    }//GEN-LAST:event_btnBeliActionPerformed

    private void fKuantitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKuantitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fKuantitasActionPerformed

    private void btnTambahProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdActionPerformed
        String str1 = fIDProduk.getText();
        String str2 = fNamaProduk.getText();
        String str3 = fHarga.getText();
        String str4 = fStok.getText();
        
        if(str1.isEmpty()||str2.isEmpty()||str3.isEmpty()||str4.isEmpty()){
        JOptionPane.showMessageDialog(this, "Harap isi seluruh Field","Coba Lagi",JOptionPane.ERROR_MESSAGE);
        
        }else{
            controller.setIdProduk(str1);
            controller.setnamaProd(str2);
            controller.setHarga(parseDouble(str3));
            controller.setStok(Integer.parseInt(str4));
            controller.simpanDataProd();
            fIDProduk.setText("");
            fNamaProduk.setText("");
            fHarga.setText("");
            fStok.setText("");
            
        
        
        }
    }//GEN-LAST:event_btnTambahProdActionPerformed

    private void fNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNamaProdukActionPerformed

    private void fStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fStokActionPerformed

    private void tabel2ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel2ubahMouseClicked
    fNamaUbah.setText(tabel2ubah.getValueAt(tabel2ubah.getSelectedRow(), 1).toString());
  fHargaUbah.setText(tabel2ubah.getValueAt(tabel2ubah.getSelectedRow(), 2).toString());
  fStokubah.setText(tabel2ubah.getValueAt(tabel2ubah.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tabel2ubahMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String str1 = fNamaUbah.getText();
        String str2 = fHargaUbah.getText();
        String str3 = fStokubah.getText();
        String id_prod = tabel2ubah.getValueAt(tabel2ubah.getSelectedRow(), 0).toString();
        if(str1.isEmpty()||str2.isEmpty()||str3.isEmpty()){
        JOptionPane.showMessageDialog(this, "Harap isi seluruh Field","Coba Lagi",JOptionPane.ERROR_MESSAGE);
        
        }else{
            controller.setIdProduk(id_prod);
            controller.setnamaProd(str1);
            controller.setHarga(parseDouble(str2));
            controller.setStok(Integer.parseInt(str3));
            controller.updateData();
            fNamaUbah.setText("");
            fHargaUbah.setText("");
            fStokubah.setText("");
            tampilData();
        
        
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
    int jawab;
    
    if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
      st = cn.createStatement();
      st.executeUpdate("DELETE FROM produk WHERE id_produk ='"
          + tabModel2.getValueAt(tabel2ubah.getSelectedRow(), 0) + "'");
      tampilData();
      fNamaUbah.setText("");
        fHargaUbah.setText("");
        fStokubah.setText("");
        tampilData();
    }
  } catch (Exception e) {
    e.printStackTrace();
  }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void fNamaUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNamaUbahActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        controller.kurangiStok();
        controller.simpanDataTrans();
        controller.getIdTransaksi();
        controller.simpanDataDetailTrans(); 
        
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHalamanUtama;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambahProd;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.JButton btnUbahProduk;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fHarga;
    private javax.swing.JTextField fHargaUbah;
    private javax.swing.JTextField fIDProduk;
    private javax.swing.JTextField fKuantitas;
    private javax.swing.JTextField fNamaProduk;
    private javax.swing.JTextField fNamaUbah;
    private javax.swing.JPasswordField fPassword;
    private javax.swing.JTextField fSearchHalamanUtama;
    private javax.swing.JTextField fStok;
    private javax.swing.JTextField fStokubah;
    private javax.swing.JTextField fUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMenuUtama;
    private javax.swing.JPanel jPanelNota;
    private javax.swing.JPanel jPanelTambahData;
    private javax.swing.JPanel jPanelTombol;
    private javax.swing.JPanel jPanelUbahData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lJumlahBeli;
    private javax.swing.JLabel lNamaKasir;
    private javax.swing.JLabel lTotalHarga;
    private javax.swing.JTable tabel1pembelian;
    private javax.swing.JTable tabel2ubah;
    private javax.swing.JTable tabel3nota;
    // End of variables declaration//GEN-END:variables
}
